added some minor improvements
t-mullen/video-stream-merger pull request #4
Opened 2017-07-06 09:14 UTC by paul-em

Awesome work you did here. 
I added/changed a couple of small things:
Some body closing tags were before the scripts, which caused an error in Edge for me.
Just after that, I found out that Edge does not work at all xD - so i implemented a support check and a fallback to just display the first added stream in case it does not work. Now I am not 100% sure this is the best way to do it, but I think it is better than failing silently, also there is a supported flag now, so one can check if it is supported and react accordingly.

Other than that i just changed the URL.createObjectURL to srcObject, because it is the new standard.

2017-07-06 17:50 UTC, t-mullen requested changes
Edge does not have many of the features required for this to work. I think throwing an error if support is missing would be better.

Thanks for the PR :)

2017-07-06 17:50 UTC, RationalCoding commented on dist/video-stream-merger.js
> +    return
Please throw an error here instead of returning, so it doesn't fail silently.

`throw new Error('Unsupported browser')`

2017-07-06 17:53 UTC, RationalCoding commented on src/index.js
> +    self._canvas = null
No need to check support here.

2017-07-06 17:54 UTC, RationalCoding commented on src/index.js
> +    self.result = self._fallbackStream
This won't be needed if we are just throwing an error. If Edge support is added, it should have the same functionality as other browsers.

2017-07-06 18:03 UTC, RationalCoding commented on dist/video-stream-merger.js
> -  self._container = document.createElement('div')
Since a hidden div doesn't seem to be needed, could you also remove the reference to `self._container` in `removeStream`

2017-07-06 18:04 UTC, RationalCoding commented
Good to see that srcObject removes the need for a hidden div. One less hack, so thanks!

2017-07-09 14:53 UTC, paul-em commented on dist/video-stream-merger.js
> +    return
Fair enough - changed it to not fail silently anymore. Also I added the support check inside of the constructor so polyfills can kick in first if present.

2017-07-09 19:55 UTC, RationalCoding commented on dist/video-stream-merger.js
> +  var audioSupport = !!(AudioContext && (new AudioContext()).createMediaStreamDestination)
The AudioContext constructor can only be called once. Could you change this to `!!(AudioContext && (self._audioCtx = new AudioContext()).createMediaStreamDestination)` and remove the corresponding line below.

2017-07-09 19:55 UTC, RationalCoding commented
Great! Just getting an issue with the AudioContext constructor being called twice, but make that change and should be good to merge.

2017-07-09 22:55 UTC, paul-em commented
Alright! All set

2017-07-09 23:13 UTC, merged

2017-07-09 23:15 UTC, RationalCoding commented
Released as `2.1.0`. Thanks again!